import React, { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, LogOut, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { fetchPatientById, updatePatient, dischargePatient, deletePatient } from '../services/patientService';
import { fetchAppointments } from '../services/appointmentService';
import StatusBadge from '../components/StatusBadge';

export default function PatientDetail() {
  const { patientId } = useParams(); const navigate = useNavigate();
  const [patient, setPatient] = useState(null); const [appointments, setAppointments] = useState([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(false); const [form, setForm] = useState({});
  useEffect(() => { (async () => { try { const [patientRes, appointmentRes] = await Promise.all([fetchPatientById(patientId), fetchAppointments({ patientId, limit: 100 })]); setPatient(patientRes.data); setForm(patientRes.data || {}); setAppointments(appointmentRes.data || []); } catch (error) { toast.error(error.response?.data?.message || 'Unable to load patient.'); } finally { setLoading(false); } })(); }, [patientId]);
  if (loading) return <div className="p-12 text-center text-xs text-zinc-400">Loading patient record...</div>;
  if (!patient) return <div className="p-12 text-center text-xs text-zinc-400">Patient record not found.</div>;
  const save = async event => { event.preventDefault(); try { const response = await updatePatient(patientId, { ...form, age: Number(form.age) }); setPatient(response.data); setEditing(false); toast.success('Patient record updated.'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to update patient.'); } };
  const discharge = async () => { try { const response = await dischargePatient(patientId); setPatient(response.data); toast.success('Patient discharged.'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to discharge patient.'); } };
  const remove = async () => { try { await deletePatient(patientId); toast.success('Patient deleted.'); navigate('/patients'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to delete patient.'); } };
  return <div className="max-w-5xl mx-auto space-y-6 animate-fade-in"><button onClick={() => navigate('/patients')} className="inline-flex items-center gap-1 text-xs font-bold text-zinc-500"><ArrowLeft className="w-4 h-4" /> Patient directory</button><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-zinc-400 font-bold">{patient.patientId}</p><h1 className="text-3xl font-extrabold text-zinc-900">{patient.name}</h1><div className="mt-2"><StatusBadge status={patient.status} /></div></div><div className="flex gap-2"><button onClick={() => setEditing(!editing)} className="px-4 py-2.5 rounded-full bg-[#4F7CFF] text-white text-xs font-bold">{editing ? 'Cancel edit' : 'Edit record'}</button>{patient.status !== 'Discharged' && <button onClick={discharge} title="Discharge patient" className="p-3 rounded-full border border-[#ECECF3] text-amber-500"><LogOut className="w-4 h-4" /></button>}<button onClick={remove} title="Delete patient" className="p-3 rounded-full border border-[#ECECF3] text-red-500"><Trash2 className="w-4 h-4" /></button></div></div>{editing ? <form onSubmit={save} className="bg-white border border-[#ECECF3] rounded-[22px] p-5 grid grid-cols-1 md:grid-cols-2 gap-4">{['name','age','gender','disease','doctor','phone','address','emergencyContact'].map(field => <input key={field} value={form[field] || ''} onChange={e => setForm({ ...form, [field]: e.target.value })} placeholder={field} className="input" />)}<button className="md:col-span-2 justify-self-end px-5 py-2.5 rounded-full bg-zinc-900 text-white text-xs font-bold">Save patient</button></form> : <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div className="bg-white border border-[#ECECF3] rounded-[22px] p-6 grid grid-cols-2 gap-5 text-xs">{[['Age',patient.age],['Gender',patient.gender],['Disease',patient.disease],['Doctor',patient.doctor],['Phone',patient.phone],['Admission',patient.admissionDate]].map(([label,value]) => <div key={label}><p className="text-zinc-400 font-semibold">{label}</p><p className="mt-1 font-bold text-zinc-800">{value || 'Not provided'}</p></div>)}</div><div className="bg-white border border-[#ECECF3] rounded-[22px] p-6"><h2 className="font-bold text-zinc-800 flex items-center gap-2"><CalendarDays className="w-4 h-4 text-[#4F7CFF]" /> Appointment history</h2><div className="mt-4 space-y-3">{appointments.map(item => <div key={item.appointmentId || item._id} className="border-b border-[#ECECF3] pb-3 text-xs"><p className="font-bold text-zinc-700">{item.date} at {item.time}</p><p className="text-zinc-400">{item.type} with {item.doctor} · {item.status}</p></div>)}{!appointments.length && <p className="text-xs text-zinc-400">No appointment history.</p>}</div></div></div>}</div>;
}
