import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { changePassword } from '../services/authService';
import { useAuthContext } from '../context/AuthContext';

export default function Settings() {
  const { user } = useAuthContext();
  const [passwords, setPasswords] = useState({ oldPassword: '', newPassword: '', confirmPassword: '' });
  const submit = async event => { event.preventDefault(); if (passwords.newPassword !== passwords.confirmPassword) { toast.error('New passwords do not match.'); return; } try { await changePassword({ oldPassword: passwords.oldPassword, newPassword: passwords.newPassword }); toast.success('Password changed successfully.'); setPasswords({ oldPassword: '', newPassword: '', confirmPassword: '' }); } catch (error) { toast.error(error.response?.data?.message || 'Unable to change password.'); } };
  return <div className="max-w-3xl mx-auto space-y-6 animate-fade-in"><div><h1 className="text-3xl font-extrabold text-zinc-900">Settings</h1><p className="text-xs text-zinc-400 font-semibold mt-1">Manage your account and security preferences.</p></div><section className="bg-white border border-[#ECECF3] rounded-[22px] p-6"><h2 className="font-bold text-zinc-800">Account profile</h2><div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 text-xs"><div><p className="text-zinc-400 font-semibold">Name</p><p className="mt-1 font-bold text-zinc-800">{user?.name || 'Administrator'}</p></div><div><p className="text-zinc-400 font-semibold">Email</p><p className="mt-1 font-bold text-zinc-800">{user?.email || 'Not available'}</p></div><div><p className="text-zinc-400 font-semibold">Role</p><p className="mt-1 font-bold text-zinc-800">{user?.role || 'Administrator'}</p></div></div></section><form onSubmit={submit} className="bg-white border border-[#ECECF3] rounded-[22px] p-6 space-y-4"><h2 className="font-bold text-zinc-800">Change password</h2><input required type="password" placeholder="Current password" value={passwords.oldPassword} onChange={e => setPasswords({ ...passwords, oldPassword: e.target.value })} className="input w-full" /><input required minLength="8" type="password" placeholder="New password (8 characters minimum)" value={passwords.newPassword} onChange={e => setPasswords({ ...passwords, newPassword: e.target.value })} className="input w-full" /><input required minLength="8" type="password" placeholder="Confirm new password" value={passwords.confirmPassword} onChange={e => setPasswords({ ...passwords, confirmPassword: e.target.value })} className="input w-full" /><button className="px-5 py-2.5 rounded-full bg-[#4F7CFF] text-white text-xs font-bold">Update password</button></form></div>;
}
